version: '3.8'
services:
  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    ports:
      - $DB_HOST:$DB_PORT:5432
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - 127.0.0.1:9000:9000
      - 127.0.0.1:9001:9001
  minio_mc:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host rm local;
      /usr/bin/mc config host add --quiet --api s3v4 local http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc rb --force local/assets/;
      /usr/bin/mc mb --quiet local/assets/;
      /usr/bin/mc policy set public local/assets;
      "
